%YAML 1.2
---
batch_size: 50
clipnorm: 1.0
hidden_units: 256
learning_rate: 0.001
model_impl: LSTM
nb_epochs: 200
patience : 5
histfile : exp/history_mnist_LSTM256_lr0-001_patience5
savefile : exp/model_mnist_LSTM256_lr0-001_patience5.hdf5
flag_permute : False

